/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const tick: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen_e37463f78dd12fd3___convert__closures_____invoke___wasm_bindgen_e37463f78dd12fd3___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_e37463f78dd12fd3___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_e37463f78dd12fd3___convert__closures_____invoke___js_sys_539a17adb0323e36___Function_fn_wasm_bindgen_e37463f78dd12fd3___JsValue_____wasm_bindgen_e37463f78dd12fd3___sys__Undefined___js_sys_539a17adb0323e36___Function_fn_wasm_bindgen_e37463f78dd12fd3___JsValue_____wasm_bindgen_e37463f78dd12fd3___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_e37463f78dd12fd3___convert__closures_____invoke___web_sys_f696f210aa502a7f___features__gen_Event__Event______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_e37463f78dd12fd3___convert__closures_____invoke___bool__true_: (a: number, b: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
