use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::adr::AdrRef;
use crate::manifest::CrateDoc;

pub(crate) fn crate_note_body(doc: &CrateDoc, adrs: &[AdrRef]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {}\n", doc.name);

    match &doc.description {
        Some(description) => {
            let _ = writeln!(out, "{description}\n");
        }
        None => {
            let _ = writeln!(out, "No description in Cargo.toml.\n");
        }
    }

    let _ = writeln!(out, "## Key dependencies\n");
    if doc.dependencies.is_empty() {
        let _ = writeln!(out, "No direct dependencies declared.\n");
    } else {
        for dep in &doc.dependencies {
            let _ = writeln!(out, "- {dep}");
        }
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "## README\n");
    match &doc.readme_relative_path {
        Some(path) => {
            let _ = writeln!(out, "README present: `{path}`\n");
        }
        None => {
            let _ = writeln!(out, "No README.\n");
        }
    }

    let _ = writeln!(out, "## Governing ADRs\n");
    if adrs.is_empty() {
        let _ = writeln!(out, "No governing ADRs found.\n");
    } else {
        for adr in adrs {
            let _ = writeln!(out, "- {} — {}", adr.id, adr.title);
        }
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "See [[Decisions]] for the full ADR index.");
    out
}

pub(crate) fn overview_body(repo_name: &str, docs: &[CrateDoc]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {repo_name} — workspace overview\n");
    let _ = writeln!(
        out,
        "Generated by `architect` from the workspace manifest. {} crates.\n",
        docs.len()
    );
    let _ = writeln!(out, "## Crates\n");
    for doc in docs {
        let summary = doc
            .description
            .as_deref()
            .unwrap_or("No description in Cargo.toml.");
        let _ = writeln!(out, "- [[{}]] — {summary}", doc.name);
    }
    let _ = writeln!(out, "\nSee [[Decisions]] for the ADR linkage index.");
    out
}

pub(crate) fn decisions_index_body(index: &BTreeMap<String, (String, BTreeSet<String>)>) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Decisions index\n");
    let _ = writeln!(
        out,
        "ADR ids linked via `adr-fmt --context <crate>` (not commit-mined). See individual crate notes for per-crate governing ADRs.\n"
    );
    if index.is_empty() {
        let _ = writeln!(out, "No governing ADRs found across the workspace.");
        return out;
    }
    for (id, (title, crates)) in index {
        let cited_by = crates.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "- **{id}** — {title} — cited by: {cited_by}");
    }
    out
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use super::{crate_note_body, decisions_index_body, overview_body};
    use crate::adr::AdrRef;
    use crate::manifest::CrateDoc;

    fn doc(name: &str) -> CrateDoc {
        CrateDoc {
            name: name.to_string(),
            description: Some(format!("{name} purpose")),
            dependencies: vec!["serde".to_string()],
            readme_relative_path: Some(format!("crates/{name}/README.md")),
        }
    }

    #[test]
    fn crate_note_reports_graceful_gaps() {
        let bare = CrateDoc {
            name: "bare".to_string(),
            description: None,
            dependencies: Vec::new(),
            readme_relative_path: None,
        };

        let body = crate_note_body(&bare, &[]);

        assert!(body.contains("No description in Cargo.toml."));
        assert!(body.contains("No direct dependencies declared."));
        assert!(body.contains("No README."));
        assert!(body.contains("No governing ADRs found."));
    }

    #[test]
    fn crate_note_lists_populated_fields() {
        let populated = doc("gh-report");
        let adrs = [AdrRef {
            id: "CHE-0073".to_string(),
            title: "GH-Report Storage Remodel".to_string(),
        }];

        let body = crate_note_body(&populated, &adrs);

        assert!(body.contains("gh-report purpose"));
        assert!(body.contains("- serde"));
        assert!(body.contains("crates/gh-report/README.md"));
        assert!(body.contains("CHE-0073 — GH-Report Storage Remodel"));
    }

    #[test]
    fn overview_links_every_crate() {
        let docs = [doc("alpha"), doc("beta")];
        let body = overview_body("demo", &docs);

        assert!(body.contains("2 crates"));
        assert!(body.contains("[[alpha]]"));
        assert!(body.contains("[[beta]]"));
    }

    #[test]
    fn decisions_index_cites_crates_per_adr() {
        let mut index: BTreeMap<String, (String, BTreeSet<String>)> = BTreeMap::new();
        index.insert(
            "CHE-0073".to_string(),
            (
                "GH-Report Storage Remodel".to_string(),
                BTreeSet::from(["gh-report".to_string()]),
            ),
        );

        let body = decisions_index_body(&index);

        assert!(body.contains("CHE-0073"));
        assert!(body.contains("cited by: gh-report"));
    }
}
